version: '3.2'

services:
  db:
    restart: always
    image: postgres:10.12-alpine
    environment:
      POSTGRES_USER: "vdbm"
      POSTGRES_DB: "vulcanize_public"
      POSTGRES_PASSWORD: "password"
    volumes:
     - vulcanizedb_db_data:/var/lib/postgresql/data
    expose:
     - "5432"
    ports:
     - "127.0.0.1:8079:5432"

  migrations:
    restart: on-failure
    depends_on:
     - db
    build:
      context: ./../../
      cache_from:
        - alpine:latest
      dockerfile: ./dockerfiles/migrations/Dockerfile
      args:
        USER: "vdbm"
    environment:
      DATABASE_NAME: "vulcanize_public"
      DATABASE_HOSTNAME: "db"
      DATABASE_PORT: 5432
      DATABASE_USER: "vdbm"
      DATABASE_PASSWORD: "password"

  graphql:
    restart: always
    depends_on:
     - db
     - migrations
    build:
      context: ./../../
      cache_from:
       - node:alpine
      dockerfile: ./dockerfiles/postgraphile/Dockerfile
    expose:
     - "5000"
    ports:
     - "127.0.0.1:5000:5000"
    command: ["--plugins", "@graphile/pg-pubsub",
              "--subscriptions",
              "--simple-subscriptions",
              "--connection", "postgres://vdbm:password@db:5432/vulcanize_public",
              "--port", "5000",
              "-n", "0.0.0.0",
              "--schema", "public,btc,eth",
              "--append-plugins", "postgraphile-plugin-connection-filter"]

volumes:
  vulcanizedb_db_data: