[superNode]
    chain = "bitcoin"
    ipfsPath = "/root/.ipfs"

    [superNode.database]
        name     = "vulcanize_public"
        hostname = "localhost"
        port     = 5432
        user     = "ec2-user"

    [superNode.sync]
        on = true
        wsPath  = "127.0.0.1:8332"
        workers = 1
        pass = "password"
        user = "username"

    [superNode.server]
        on = true
        ipcPath = "/root/.vulcanize/btc/vulcanize.ipc"
        wsPath = "127.0.0.1:8082"
        httpPath = "127.0.0.1:8083"

    [superNode.backFill]
        on = true
        httpPath = "127.0.0.1:8332"
        frequency = 15
        batchSize = 50
        pass = "password"
        user = "username"

    [superNode.btc]
        nodeID = "ocd0"
        clientName = "Omnicore"
        genesisBlock = "000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f"
        networkID = "0xD9B4BEF9"