[superNode]
    chain = "ethereum"
    ipfsPath = "/root/.ipfs"

    [superNode.database]
        name     = "vulcanize_public"
        hostname = "localhost"
        port     = 5432
        user     = "ec2-user"

    [superNode.sync]
        on = true
        wsPath  = "ws://127.0.0.1:8546"
        workers = 1

    [superNode.server]
        on = true
        ipcPath = "/root/.vulcanize/eth/vulcanize.ipc"
        wsPath = "127.0.0.1:8080"
        httpPath = "127.0.0.1:8081"

    [superNode.backFill]
        on = true
        httpPath = "http://127.0.0.1:8545"
        frequency = 15
        batchSize = 50