[database]
    name     = "vulcanize_public"
    hostname = "localhost"
    port     = 5432
    user     = "vdbm"

[resync]
    chain = "bitcoin"
    type = "full"
    clearOldCache = true
    ipfsPath = "/root/.ipfs"
    batchSize = 1
    batchNumber = 50
    start = 0
    stop = 0

[bitcoin]
    httpPath = "127.0.0.1:8332"
    pass = "password"
    user = "username"
    nodeID = "ocd0"
    clientName = "Omnicore"
    genesisBlock = "000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f"
    networkID = "0xD9B4BEF9"