[database]
    name     = "vulcanize_public"
    hostname = "localhost"
    port     = 5432
    user     = "vdbm"

[resync]
    chain = "ethereum"
    type = "state"
    clearOldCache = true
    ipfsPath = "/root/.ipfs"
    batchSize = 5
    batchNumber = 50
    start = 0
    stop = 0

[ethereum]
    httpPath = "127.0.0.1:8545"