[superNode]
    chain = "ethereum"
    ipfsPath = "/root/.ipfs"

    [superNode.database]
        name     = "vulcanize_public"
        hostname = "localhost"
        port     = 5432
        user     = "ec2-user"

    [superNode.sync]
        on = true
        wsPath  = "ws://127.0.0.1:8546"
        workers = 1

    [superNode.server]
        on = true
        ipcPath = "/root/.vulcanize/vulcanize.ipc"
        wsPath = "127.0.0.1:8080"

    [superNode.backFill]
        on = false
        httpPath = ""
        frequency = 5
        batchSize = 50